name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.100

      - name: Install Tools
        run: dotnet tool restore

      - name: Publish
        run: dotnet run Publish

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          skip_app_build: true
          action: 'upload'
          app_location: 'publish/app/public'